### ISSUE TITLE
How to merge the Wiki?

### ISSUE THREAD

**Issue by sebastianbachmann** [JayPanoz/Soma#1]
Hi @JayPanoz as you requested ;) , i forked the repository and moved the FAQ into the [Wiki](https://github.com/sebastianbachmann/Soma/wiki/Friendly-Asked-Questions) section. The thing is, i am not really sure how to send you a pull request to merge the wiki. Any ideas?

**Comment by JayPanoz** [comment]
Wow cool thanks. 

So don’t worry, it’s up to me to cherry pick the forked Wiki now. 

For the record, how-to can be found there: https://gist.github.com/larrybotha/10650410

**Comment by JayPanoz** [comment]
OK so wikis are tough, especially when there wasn't a wiki in the first place, at the time the repo was forked (my bad). Got an insane amount of errors while trying to merge that and ended up copying/pasting .md files like a poor man. Then pull.

I'm so sorry my terminal-fu didn't do the trick. Tried a lot of stuff, to no avail.

If someone has some solution for this particular case: merging a wiki from a fork while that wiki didn't exist in the first place, let me know—cos yeah, there's no support for wiki's pull requests.
